import {ENUM_ROUTES} from '@/enums/routes'

const DOCS_ROUTES = [ENUM_ROUTES.DOCS, ENUM_ROUTES.DOCS_INSTALLATION]
const COMPONENTS_ROUTES = [ENUM_ROUTES.COMPONENTS, ENUM_ROUTES.COMPONENTS_BADGE, ENUM_ROUTES.COMPONENTS_BUTTON, ENUM_ROUTES.COMPONENTS_INPUT]

export {COMPONENTS_ROUTES, DOCS_ROUTES}
