import {ENUM_ROUTES} from '@/enums/routes'

const DOCS_ROUTES = [ENUM_ROUTES.DOCS, ENUM_ROUTES.DOCS_INSTALLATION]
const COMPONENTS_ROUTES = [
  ENUM_ROUTES.COMPONENTS,
  ENUM_ROUTES.COMPONENTS_ACCORDION,
  ENUM_ROUTES.COMPONENTS_ALERT,
  ENUM_ROUTES.COMPONENTS_AVATAR,
  ENUM_ROUTES.COMPONENTS_BADGE,
  ENUM_ROUTES.COMPONENTS_BREADCRUMB,
  ENUM_ROUTES.COMPONENTS_BUTTON,
  ENUM_ROUTES.COMPONENTS_CARD,
  ENUM_ROUTES.COMPONENTS_CAROUSEL,
  ENUM_ROUTES.COMPONENTS_CHECKBOX,
  ENUM_ROUTES.COMPONENTS_DIVIDER,
  ENUM_ROUTES.COMPONENTS_INPUT,
  ENUM_ROUTES.COMPONENTS_PROGRESS,
  ENUM_ROUTES.COMPONENTS_SKELETON,
  ENUM_ROUTES.COMPONENTS_SPINNER,
]

export {COMPONENTS_ROUTES, DOCS_ROUTES}
