import './globals.scss'
import 'react-toastify/dist/ReactToastify.css'

import type {Metadata} from 'next'
import {Martian_Mono} from 'next/font/google'

const martian = Martian_Mono({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${martian.className} scrollbar-thumb-white/10 scrollbar-track-white/10 w-full antialiased`}>{children}</body>
    </html>
  )
}
